version: '3'

services:
  backend:
    build:
      context: ./nest-api
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./nest-api:/usr/src/app
  frontend:
    build:
      context: ./react-frontend
      dockerfile: ./Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./react-frontend:/usr/src/app
    depends_on:
      - "backend"